---
namespace: illumio
name: core
version: 0.2.5
readme: README.md
authors:
  - Duncan Sommerville (@dsommerville-illumio)
description: Ansible collection for managing resources in the Illumio Policy Compute Engine
license_file: LICENSE
tags:
  - illumio
  - networking
  - security
  - linux
  - windows
dependencies:
  ansible.windows: '*'
  community.general: '*'
  kubernetes.core: '*'
repository: https://github.com/illumio/illumio.core
build_ignore:
  - '.github'
  - '.gitignore'
  - '.yamllint'
  - 'Makefile'
  - '*.env'
  - '*.tar.gz'
  - 'build'
  - 'dist'
  - 'local'
  - 'venv'
  - 'molecule'
  - '**/integration_config.yml'
  - '**/inventory'
