---
- name: "Set illumio-ven-ctl path for Linux"
  ansible.builtin.set_fact:
    illumio_ven_ctl: /opt/illumio_ven/illumio-ven-ctl
  tags:
    - always

- name: "Start VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} start"
  register: result
  changed_when: "'already started' not in result.stdout"
  tags:
    - never
    - ven_start

- name: "Stop VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} stop"
  register: result
  changed_when: "'FAILED' not in result.stdout"
  tags:
    - never
    - ven_stop

- name: "Restart VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} restart"
  register: result
  changed_when: result.rc == 0
  tags:
    - never
    - ven_restart

- name: "Suspend the VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} suspend"
  register: result
  changed_when: "'The VEN has been suspended' in result.stdout"
  tags:
    - never
    - ven_suspend

- name: "Unsuspend VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} unsuspend"
  register: result
  changed_when: "'The VEN has been unsuspended' in result.stdout"
  tags:
    - never
    - ven_unsuspend

- name: "Deactivate VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} deactivate"
  register: result
  changed_when: "'The VEN has been deactivated' in result.stdout"
  tags:
    - never
    - ven_deactivate

- name: "Unpair VEN"
  become: true
  ansible.builtin.command: "{{ illumio_ven_ctl }} unpair {{ illumio_ven_firewall_restore }}"
  register: result
  changed_when: result.rc == 0
  tags:
    - never
    - ven_unpair

- name: "Stat VEN control tool"
  become: true
  ansible.builtin.stat:
    path: "{{ illumio_ven_ctl }}"
  register: ven_cli
  tags:
    - always
    - ven_status

- name: "Check VEN status"
  when: ven_cli.stat.exists
  tags:
    - always
    - ven_status
  block:

    - name: "Get VEN status"
      become: true
      ansible.builtin.command: "{{ illumio_ven_ctl }} status"
      failed_when: ven_status.rc is not defined or ven_status.rc > 1
      register: ven_status
      changed_when: false

    - name: "Print VEN status"
      ansible.builtin.debug:
        msg: "{{ ven_status.stdout_lines }}"
