---
- name: "Set illumio-ven-ctl path for Windows"
  ansible.builtin.set_fact:
    ven_ctl: C:\Program Files\Illumio\illumio-ven-ctl.ps1
  tags:
    - always

- name: "Stat VEN control tool"
  become: true
  ansible.windows.win_stat:
    path: "{{ ven_ctl }}"
  register: ven_cli
  tags:
    - always

- name: "Fail on missing VEN control tool"
  ansible.builtin.fail:
    msg: "Missing VEN control tool at {{ ven_ctl }}"
  when: not ven_cli.stat.exists
  tags:
    - always

- name: "Start VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" start
  register: ven_result
  changed_when: "'already started' not in ven_result.stdout"
  tags:
    - never
    - ven_start

- name: "Stop VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" stop
  register: ven_result
  changed_when: "'FAILED' not in ven_result.stdout"
  tags:
    - never
    - ven_stop

- name: "Restart VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" restart
  register: ven_result
  changed_when: ven_result.rc == 0
  tags:
    - never
    - ven_restart

- name: "Suspend the VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" suspend
  register: ven_result
  changed_when: "'The VEN has been suspended' in ven_result.stdout"
  tags:
    - never
    - ven_suspend

- name: "Unsuspend VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" unsuspend
  register: ven_result
  changed_when: "'The VEN has been unsuspended' in ven_result.stdout"
  tags:
    - never
    - ven_unsuspend

- name: "Deactivate VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" deactivate
  register: ven_result
  changed_when: "'The VEN has been deactivated' in ven_result.stdout"
  tags:
    - never
    - ven_deactivate

- name: "Unpair VEN"
  become: true
  ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" unpair {{ illumio_ven_firewall_restore }}
  register: ven_result
  changed_when: ven_result.rc == 0
  tags:
    - never
    - ven_unpair

- name: "Check VEN status"
  when: "'ven_unpair' not in ansible_run_tags"
  tags:
    - always
    - ven_status
  block:

    - name: "Get VEN status"
      become: true
      ansible.windows.win_command: powershell.exe -file "{{ ven_ctl }}" status
      failed_when: ven_status.rc is not defined or ven_status.rc > 1
      register: ven_status
      changed_when: false

    - name: "Print VEN status"
      ansible.builtin.debug:
        msg: "{{ ven_status.stdout_lines | replace('\\t', ' ') }}"
